### PR TITLE
v2.0.0

### PR DESCRIPTION
**Pull request by notgull**
- **Breaking:** Remove interior mutability from `Rng`. (#47)
- Add a `fork()` method. (#49)
- Add a `no_std` mode. (#50)
- Add an iterator selection function. (#51)
- Add a `choose_multiple()` function for sampling several elements from an iterator. (#55)
- Use the `getrandom` crate for seeding on WebAssembly targets if the `js` feature is enabled. (#60)

### CODE REVIEW

**Comment by notgull** [comment]
As this is a breaking release, we should probably consider if there are any other breaking changes that we want to make before we release.

**Comment by notgull** [comment]
@smol-rs/admins Any objections to publishing this?

**Comment by taiki-e** [comment]
I was thinking of replacing the dependency on `instant` or making it easier to use. Currently, `instant` is virtually a public dependency as the user has to directly depend on `instant` to enable the `wasm-bindgen` feature.

Specifically, I was thinking of either providing something like a `wasm-bindgen` feature that would enable the `wasm-bindgen` feature of `instant`, or providing similar features by directly depending on `wasm-bindgen` (i.e., drop `instant`). Probably, it is also okay to start with the former and switch to the latter, though.

That said, I don't have the bandwidth to work on it right now, so if other admins are happy with the current wasm-unknown-unknown support situation, I'm fine with that.

**Comment by SilvanCodes** [comment]
Looking forward to use `fastrand` with `Sync` and `choice`!

**Comment by notgull** [comment]
Alright, any other objections? @smol-rs/admins

**Pull request merged**
