### PR TITLE
added char() implementations and tests

### LINKED ISSUE #24: Needs `char` generator
Type `char` is missing and I needed it. Will supply a PR for it shortly.

### PR DESCRIPTION
**Pull request by BartMassey**
This PR provides implementations of `char` for fastrand, together with some tests; closes #24.

### CODE REVIEW

**Comment by taiki-e** [comment]
The title says that tests are added, but it seems that no tests are actually added.

**Comment by BartMassey** [comment]
Forgot to add the tests. Thanks for catching this.

**Review by taiki-e — APPROVED** [review]
Thanks!

**Comment by taiki-e** [comment]
Published in 1.7.0.

**Pull request merged**
