### PR TITLE
v2.0.2

### PR DESCRIPTION
**Pull request by notgull**
- Slight restructuring of the `with_seed` function. (#79)

### CODE REVIEW

**Comment by taiki-e** [comment]
Since #76 is about the comment in the benchmark code, nothing seems to have changed in the documentation of fastrand itself.

**Comment by notgull** [comment]
I see...

Looking at https://github.com/smol-rs/fastrand/commit/dda0fe824b078bc844300db86021c2552465c468 it's also a difference that's worth releasing, even if it's not really much of a change

**Comment by taiki-e** [comment]
> Looking at [dda0fe8](https://github.com/smol-rs/fastrand/commit/dda0fe824b078bc844300db86021c2552465c468) it's also a difference that's worth releasing, even if it's not really much of a change

I think the compiler could optimize it, but it indeed could be somewhat useful in debug mode.

**Comment by notgull** [comment]
I'll take that as an "okay".

**Pull request merged**
