### PR TITLE
Implement RngCore

### PR DESCRIPTION
**Pull request by DE0CH**
Some libraries such as `statrs` accepts random number generators that implement the `rand::Rng` trait. This PR implements that trait (by implementing `rand_core::RngCore`). This will make it more useful to be integrated into other projects.

### CODE REVIEW

**Comment by DE0CH** [comment]
[msrv (1.34)](https://github.com/smol-rs/fastrand/pull/30#logs) fails because `rand_core` uses `alloc`. I don't think there's anything I can do to address that.

**Comment by taiki-e** [comment]
We do not want to have 0.x crates as public dependencies. See [C-STABLE](https://rust-lang.github.io/api-guidelines/necessities.html#public-dependencies-of-a-stable-crate-are-stable-c-stable) for more.

Thanks anyway for the PR!

**Comment by DE0CH** [comment]
I see. But I still think this having this would greatly improve the usability of this library. Can we do it like `rand_mt` where dependencies on `rand_core` is optional? Or can I make a fork called `rand_fast` which depends on `rand_core` and start with version 0.x?

**Comment by taiki-e** [comment]
One of the ways to handle such cases is to use versioned optional feature names like rand_core06. ([example](https://github.com/async-rs/async-std/blob/798ce31e1095af16fe760aa97e86b924324bf118/Cargo.toml#L59-L60)) However, maintenance is a bit more complicated because rand use semver-trick

**Pull request closed without merging**
