### PR TITLE
v2.3.0

### PR DESCRIPTION
**Pull request by notgull**
- Accept `IntoIterator` in `choose_multiple` functions instead of just `Iterator`. (#92)

### CODE REVIEW

**Comment by notgull** [comment]
> LGTM aside from CI failure (due to [rustwasm/wasm-bindgen#4304](https://github.com/rustwasm/wasm-bindgen/issues/4304)).

Fixed via #96

**Comment by taiki-e** [comment]
Hmm, I guess it break compatibility with pre-1.51 rustc...

**Comment by notgull** [comment]
What do you mean? We have 1.36 in the CI and it seems to pass.

**Comment by taiki-e** [comment]
resolver is unknown field in 1.36, but unstable field in 1.50, so build will be fail in 1.50 even if pass in 1.36.

**Comment by taiki-e** [comment]
(See also https://github.com/rust-lang/cargo/pull/13505#issuecomment-1975267586 for Cargo's behavior on unknown fields.)

**Comment by notgull** [comment]
Hmm, is there a better solution to this?

**Comment by taiki-e** [comment]
> Hmm, is there a better solution to this?

Perhaps:
- Revert #96 
- Run `echo '#[workspace]' >> Cargo.toml` and `echo 'resolver = "2"' >> Cargo.toml` before "Test wasm" in CI config

The best way would be to fix wasm-bindgen.

**Comment by taiki-e** [comment]
wasm-bindgen issue has been fixed in 0.2.98 (https://github.com/rustwasm/wasm-bindgen/pull/4327), so just reverting #96 would be enough.

**Comment by taiki-e** [comment]
#96 has been reverted in https://github.com/smol-rs/fastrand/pull/97.

**Review by taiki-e — APPROVED** [review]

**Pull request merged**
